spring:
  application:
    name: manydbs
  h2:
    console:
      enabled: true
  datasource:
    users:
      url: jdbc:h2:mem:testdb
      username: sa
      password:
      driverClassName: org.h2.Driver
    sales:
      url: jdbc:postgresql://postgres:5433/postgres
      username: postgres
      password: postgres
      driverClassName: org.postgresql.Driver
    products:
      url: jdbc:mysql://mysql:3306/mysql?allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: abcABC123*
      driverClassName: com.mysql.cj.jdbc.Driver

